version: "3"

networks: 
  db: 
  app: 

services:
  db:
    image: mongo:3.4
    networks: 
      - db
  server:
    build: server
    volumes:
      - ./server:/server
    working_dir: /server
    command: npm start
    networks: 
      - db
      - app
    ports:
      - 3000:3000
    depends_on: 
      - db
  app:
    image: nginx:1.13
    volumes:
      - ./app/dist:/usr/share/nginx/html/
    networks: 
      - app
    ports:
      - 80:80
    depends_on: 
      - server